version: '3.7'

services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - deepgram_audio:/var/lib/postgresql/data

volumes:
  deepgram_audio: